name: Build Python for Android (Latest Versions)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # 自动指向最新的 Ubuntu LTS 版本

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置最新 Android NDK（官方推荐方式）
      - name: Setup latest Android NDK
        uses: android-actions/setup-android-ndk@v1
        with:
          ndk-version: "latest"  # 自动获取最新稳定版 NDK
          cache: true  # 启用缓存加速后续构建

      # 3. 验证 NDK 安装
      - name: Verify NDK
        run: |
          echo "NDK 路径: $ANDROID_NDK_HOME"
          $ANDROID_NDK_HOME/ndk-build --version

      # 4. 使用系统默认 Python（Ubuntu 预装的 Python 3.10）
      - name: Check system Python
        run: |
          python3 --version  # 默认是 3.10.x
          echo "Python 路径: $(which python3)"

      # 5. 下载 Python 源码（指定版本，例如 3.11.0）
      - name: Download Python source
        run: |
          wget -q https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tgz
          tar -xzf Python-3.11.0.tgz
          mv Python-3.11.0 cpython

      # 6. 交叉编译配置
      - name: Configure and compile
        run: |
          cd cpython
          export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
          
          # 使用系统 Python 3.10 作为 host python
          python3 ./configure \
            --host=aarch64-linux-android \
            --build=x86_64-linux-gnu \
            --enable-shared \
            --disable-ipv6 \
            CC=$TOOLCHAIN/bin/aarch64-linux-android21-clang \
            CXX=$TOOLCHAIN/bin/aarch64-linux-android21-clang++ \
            AR=$TOOLCHAIN/bin/aarch64-linux-android-ar \
            READELF=$(which readelf) \
            ac_cv_file__dev_ptmx=yes \
            ac_cv_file__dev_ptc=no

          make -j$(nproc)

      # 7. 打包产物
      - name: Package artifacts
        run: |
          mkdir -p android-root
          cd cpython
          make install prefix=$GITHUB_WORKSPACE/android-root
          tar -czvf python-android.tar.gz -C android-root .

      # 8. 上传结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-android-build
          path: python-android.tar.gz