name: Python for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          
          # 安装 Python 3.12 和必要的开发包
          sudo apt install -y python3.12 python3.12-dev python3.12-venv python3.12-distutils
          
          # 创建 Python 3.12 虚拟环境以避免系统 pip 冲突
          python3.12 -m venv /opt/python3.12
          source /opt/python3.12/bin/activate
          
          # 安装基础构建工具
          sudo apt install -y build-essential zlib1g-dev libffi-dev libssl-dev libbz2-dev \
                              libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
                              libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
                              liblzma-dev git tar unzip binutils
          
          # 确保使用正确的 Python 和 pip 版本
          python3 --version
          pip3 --version || echo "System pip not available, will use venv pip"

      - name: Set up Android NDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: "25.2.9519653"

      - name: Set ANDROID_NDK_HOME
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT" >> $GITHUB_PATH

      - name: Download Python Source
        run: |
          PY_VERSION="3.12.0"  # 目标Python版本
          wget https://www.python.org/ftp/python/$PY_VERSION/Python-$PY_VERSION.tgz
          tar -xf Python-$PY_VERSION.tgz
          mv Python-$PY_VERSION cpython

      - name: Download and Extract zlib
        run: |
          wget https://github.com/madler/zlib/archive/refs/tags/v1.2.13.tar.gz -O zlib-1.2.13.tar.gz
          tar -xvf zlib-1.2.13.tar.gz
          cd zlib-1.2.13

      - name: Set Cross-Compile Tools
        run: |
          export READELF=$(which readelf)
          if [ ! -f "$READELF" ]; then
            sudo apt install -y binutils
            export READELF=$(which readelf)
          fi
          echo "READELF=$READELF" >> $GITHUB_ENV
          export AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar
          echo "AR=$AR" >> $GITHUB_ENV

      - name: Configure and Compile Python
        run: |
          cd cpython
          export CONFIG_SITE=config.site
          cat <<EOF > $CONFIG_SITE
          ac_cv_file__dev_ptmx=yes
          ac_cv_file__dev_ptc=no
          EOF

          # 使用虚拟环境中的 Python 作为 build python
          BUILD_PYTHON=/opt/python3.12/bin/python3
          ./configure --host=aarch64-linux-android --build=x86_64-linux-gnu \
                      --disable-optimizations \
                      --disable-ipv6 \
                      --with-build-python=$BUILD_PYTHON \
                      CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang \
                      CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
                      AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar \
                      RANLIB=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ranlib \
                      READELF=$READELF

          echo "Configuration completed"
          make -j$(nproc)

      - name: Compile zlib
        run: |
          cd zlib-1.2.13
          ./configure
          make -j$(nproc)

      - name: Install Python and zlib to Simulated Android Root
        run: |
          mkdir -p $GITHUB_WORKSPACE/android-rootfs/data
          
          cd cpython
          make install prefix=$GITHUB_WORKSPACE/android-rootfs/data
          
          cd ../zlib-1.2.13
          make install prefix=$GITHUB_WORKSPACE/android-rootfs/data

          echo "Contents of android-rootfs/data:"
          ls -lh $GITHUB_WORKSPACE/android-rootfs/data

      - name: Package Artifacts
        run: |
          tar -czvf python-zlib-android-data.tar.gz -C android-rootfs/data .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-zlib-android-data
          path: python-zlib-android-data.tar.gz