name: Build Python for Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. 使用官方推荐的 NDK 安装方式
      - name: Setup Android SDK
        uses: android-actions/setup-android-sdk@v2
        with:
          ndk-version: "25.2.9519653"  # 明确指定 NDK 版本
          cmake-version: "3.22.1"      # 可选：如果需要 CMake

      # 2. 设置 Python 3.10 环境
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. 安装编译依赖
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev libffi-dev libssl-dev \
                             libbz2-dev libreadline-dev libsqlite3-dev wget curl

      # 剩余步骤保持不变...
      - name: Download Python 3.12
        run: |
          wget -q https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tar.xz
          tar -xf Python-3.12.0.tar.xz
          mv Python-3.12.0 cpython

      - name: Configure and build
        run: |
          cd cpython
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653
          export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
          
          ./configure \
            --host=aarch64-linux-android \
            --build=x86_64-linux-gnu \
            --enable-shared \
            --with-build-python=$(which python3) \
            CC=$TOOLCHAIN/bin/aarch64-linux-android21-clang \
            CXX=$TOOLCHAIN/bin/aarch64-linux-android21-clang++ \
            AR=$TOOLCHAIN/bin/aarch64-linux-android-ar \
            ac_cv_file__dev_ptmx=yes

          make -j$(nproc)

      - name: Package artifacts
        run: |
          mkdir -p android-root
          cd cpython
          make install prefix=$GITHUB_WORKSPACE/android-root
          tar -czvf python-android.tar.gz -C android-root .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-android-build
          path: python-android.tar.gz