name: Build Python for Android (Latest NDK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码（使用官方维护的 checkout）
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Python 环境（显式指定 3.10）
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. 安装 NDK（改用官方推荐的安装方式）
      - name: Set up Android NDK
        uses: android-actions/setup-android-ndk@v2  # 注意改用 v2
        with:
          ndk-version: "25.2.9519653"  # 明确指定稳定版本
          cache: true

      # 4. 安装编译依赖
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev libffi-dev libssl-dev \
                             libbz2-dev libreadline-dev libsqlite3-dev wget curl

      # 5. 下载 Python 3.12 源码
      - name: Download Python 3.12
        run: |
          wget -q https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tar.xz
          tar -xf Python-3.12.0.tar.xz
          mv Python-3.12.0 cpython

      # 6. 交叉编译配置
      - name: Configure and build
        run: |
          cd cpython
          export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
          
          ./configure \
            --host=aarch64-linux-android \
            --build=x86_64-linux-gnu \
            --enable-shared \
            --with-build-python=$(which python3) \
            CC=$TOOLCHAIN/bin/aarch64-linux-android21-clang \
            CXX=$TOOLCHAIN/bin/aarch64-linux-android21-clang++ \
            AR=$TOOLCHAIN/bin/aarch64-linux-android-ar \
            ac_cv_file__dev_ptmx=yes

          make -j$(nproc)

      # 7. 打包产物
      - name: Package artifacts
        run: |
          mkdir -p android-root
          cd cpython
          make install prefix=$GITHUB_WORKSPACE/android-root
          tar -czvf python-android.tar.gz -C android-root .

      # 8. 上传结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-android-build
          path: python-android.tar.gz