name: Build Python and zlib for Android ARM64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev libffi-dev libssl-dev libbz2-dev \
                              libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
                              libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
                              liblzma-dev git tar python3 python3-pip unzip binutils
          python3 --version
          pip3 --version

      - name: Cache Android NDK
        uses: actions/cache@v4
        with:
          path: ~/android-ndk
          key: android-ndk-r21d

      - name: Download and Set Up Android NDK
        run: |
          if [ -d "$HOME/android-ndk/android-ndk-r21d" ]; then
            echo "NDK already exists, skipping download."
          else
            echo "Downloading NDK..."
            mkdir -p ~/android-ndk
            wget -O ~/android-ndk/android-ndk-r21d-linux.zip https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
            unzip -o -d ~/android-ndk ~/android-ndk/android-ndk-r21d-linux.zip
          fi
          export ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r21d
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "$ANDROID_NDK_HOME" >> $GITHUB_PATH

      - name: Check if Latest Python is Installed
        run: |
          REQUIRED_PYTHON_VERSION="3.10.0"
          if python3 --version | grep -q "$REQUIRED_PYTHON_VERSION"; then
            echo "Python $REQUIRED_PYTHON_VERSION is already installed."
          else
            echo "Downloading and compiling Python..."
            wget https://www.python.org/ftp/python/$REQUIRED_PYTHON_VERSION/Python-$REQUIRED_PYTHON_VERSION.tgz
            tar -xf Python-$REQUIRED_PYTHON_VERSION.tgz
            mv Python-$REQUIRED_PYTHON_VERSION cpython
          fi

      - name: Download and Extract zlib
        run: |
          wget https://github.com/madler/zlib/archive/refs/tags/v1.2.13.tar.gz -O zlib-1.2.13.tar.gz
          tar -xvf zlib-1.2.13.tar.gz
          cd zlib-1.2.13

      - name: Set Cross-Compile Tools
        run: |
          export CROSS_COMPILE=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-
          export READELF=$(which readelf)
          if [ ! -f "$READELF" ]; then
            sudo apt install -y binutils
            export READELF=$(which readelf)
          fi
          echo "READELF=$READELF" >> $GITHUB_ENV
          export AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar
          echo "AR=$AR" >> $GITHUB_ENV

      - name: Configure and Compile Python
        run: |
          cd cpython
          export CONFIG_SITE=config.site
          cat <<EOF > $CONFIG_SITE
          ac_cv_file__dev_ptmx=yes
          ac_cv_file__dev_ptc=no
          EOF

          BUILD_PYTHON=$(which python3)
          ./configure --host=aarch64-linux-android --build=x86_64-linux-gnu \
                      --disable-optimizations \
                      --disable-ipv6 \
                      --with-build-python=$BUILD_PYTHON \
                      CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang \
                      CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
                      AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar \
                      RANLIB=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ranlib \
                      READELF=$READELF

          echo "Configuration completed"
          make -j$(nproc)

      - name: Compile zlib
        run: |
          cd zlib-1.2.13
          ./configure
          make -j$(nproc)

      - name: Install Python and zlib to Simulated Android Root (`/data`)
        run: |
          mkdir -p $GITHUB_WORKSPACE/android-rootfs/data
          
          # 安装 Python 和 zlib 到模拟的 /data 目录
          cd cpython
          make install prefix=$GITHUB_WORKSPACE/android-rootfs/data
          
          cd ../zlib-1.2.13
          make install prefix=$GITHUB_WORKSPACE/android-rootfs/data

          # 确保安装成功，检查文件是否在目标目录
          echo "Contents of android-rootfs/data:"
          ls -lh $GITHUB_WORKSPACE/android-rootfs/data

      - name: Package Installed Python and zlib
        run: |
          # 打包安装的 Python 和 zlib 文件
          tar -czvf python-zlib-android-data.tar.gz -C android-rootfs/data .

      - name: Upload Python and zlib Package
        uses: actions/upload-artifact@v4
        with:
          name: python-zlib-android-data
          path: python-zlib-android-data.tar.gz