name: Build Python and zlib for Android ARM64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev libffi-dev libssl-dev libbz2-dev \
                              libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
                              libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
                              liblzma-dev git tar python3 python3-pip unzip binutils
          python3 --version
          pip3 --version

      - name: Set up Android NDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: "25.2.9519653"  # 使用 GitHub Actions 提供的 NDK 版本

      - name: Set ANDROID_NDK_HOME
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT" >> $GITHUB_PATH

      - name: Get Installed Python Version
        id: python-version
        run: |
          PY_VERSION=$(python3 -c "import sys; print('.'.join(map(str, sys.version_info[:3])))")
          echo "Detected Python version: $PY_VERSION"
          echo "PY_VERSION=$PY_VERSION" >> $GITHUB_ENV
          # 下载对应版本的 Python 源代码
          echo "Downloading Python $PY_VERSION source code..."
          wget https://www.python.org/ftp/python/$PY_VERSION/Python-$PY_VERSION.tgz
          tar -xf Python-$PY_VERSION.tgz
          mv Python-$PY_VERSION cpython

      - name: Download and Extract zlib
        run: |
          wget https://github.com/madler/zlib/archive/refs/tags/v1.2.13.tar.gz -O zlib-1.2.13.tar.gz
          tar -xvf zlib-1.2.13.tar.gz
          cd zlib-1.2.13

      - name: Set Cross-Compile Tools
        run: |
          export READELF=$(which readelf)
          if [ ! -f "$READELF" ]; then
            sudo apt install -y binutils
            export READELF=$(which readelf)
          fi
          echo "READELF=$READELF" >> $GITHUB_ENV
          export AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar
          echo "AR=$AR" >> $GITHUB_ENV

      - name: Configure and Compile Python
        run: |
          cd cpython
          export CONFIG_SITE=config.site
          cat <<EOF > $CONFIG_SITE
          ac_cv_file__dev_ptmx=yes
          ac_cv_file__dev_ptc=no
          EOF

          BUILD_PYTHON=$(which python3)
          ./configure --host=aarch64-linux-android --build=x86_64-linux-gnu \
                      --disable-optimizations \
                      --disable-ipv6 \
                      --with-build-python=$BUILD_PYTHON \
                      CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang \
                      CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
                      AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar \
                      RANLIB=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ranlib \
                      READELF=$READELF

          echo "Configuration completed"
          make -j$(nproc)

      - name: Compile zlib
        run: |
          cd zlib-1.2.13
          ./configure
          make -j$(nproc)

      - name: Install Python and zlib to Simulated Android Root (`/data`)
        run: |
          mkdir -p $GITHUB_WORKSPACE/android-rootfs/data
          
          # 安装 Python 和 zlib 到模拟的 /data 目录
          cd cpython
          make install prefix=$GITHUB_WORKSPACE/android-rootfs/data
          
          cd ../zlib-1.2.13
          make install prefix=$GITHUB_WORKSPACE/android-rootfs/data

          # 确保安装成功，检查文件是否在目标目录
          echo "Contents of android-rootfs/data:"
          ls -lh $GITHUB_WORKSPACE/android-rootfs/data

      - name: Package Installed Python and zlib
        run: |
          # 打包安装的 Python 和 zlib 文件
          tar -czvf python-zlib-android-data.tar.gz -C android-rootfs/data .

      - name: Upload Python and zlib Package
        uses: actions/upload-artifact@v4
        with:
          name: python-zlib-android-data
          path: python-zlib-android-data.tar.gz
