name: Python for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev libffi-dev libssl-dev libbz2-dev \
                              libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
                              libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
                              liblzma-dev git tar python3 python3-pip unzip binutils
          python3 --version
          pip3 --version

      - name: Set up Android NDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: "25.2.9519653"  # 使用这个特定版本

      - name: Verify NDK Installation
        run: |
          echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
          echo "NDK contents:"
          ls -l $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/

      - name: Get Installed Python Version
        id: python-version
        run: |
          PY_VERSION=$(python3 -c "import sys; print('.'.join(map(str, sys.version_info[:3])))")
          echo "Detected Python version: $PY_VERSION"
          echo "PY_VERSION=$PY_VERSION" >> $GITHUB_ENV
          wget https://www.python.org/ftp/python/$PY_VERSION/Python-$PY_VERSION.tgz
          tar -xf Python-$PY_VERSION.tgz
          mv Python-$PY_VERSION cpython

      - name: Download and Extract zlib
        run: |
          wget https://github.com/madler/zlib/archive/refs/tags/v1.2.13.tar.gz -O zlib-1.2.13.tar.gz
          tar -xvf zlib-1.2.13.tar.gz

      - name: Set Cross-Compile Tools
        run: |
          # 确保使用正确的 NDK 路径
          export ANDROID_NDK_HOME="$ANDROID_NDK_ROOT"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          
          # 设置工具链路径
          TOOLCHAIN="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          echo "TOOLCHAIN=$TOOLCHAIN" >> $GITHUB_ENV
          
          # 验证工具是否存在
          export CC="$TOOLCHAIN/aarch64-linux-android21-clang"
          export CXX="$TOOLCHAIN/aarch64-linux-android21-clang++"
          export AR="$TOOLCHAIN/llvm-ar"
          export RANLIB="$TOOLCHAIN/llvm-ranlib"
          export READELF=$(which readelf)
          
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CXX=$CXX" >> $GITHUB_ENV
          echo "AR=$AR" >> $GITHUB_ENV
          echo "RANLIB=$RANLIB" >> $GITHUB_ENV
          echo "READELF=$READELF" >> $GITHUB_ENV
          
          # 验证工具存在
          ls -l $CC $CXX $AR $RANLIB

      - name: Configure and Compile Python
        run: |
          cd cpython
          export CONFIG_SITE=config.site
          cat <<EOF > $CONFIG_SITE
          ac_cv_file__dev_ptmx=yes
          ac_cv_file__dev_ptc=no
          EOF

          BUILD_PYTHON=$(which python3)
          ./configure --host=aarch64-linux-android --build=x86_64-linux-gnu \
                      --disable-optimizations \
                      --disable-ipv6 \
                      --with-build-python=$BUILD_PYTHON \
                      CC="$CC" \
                      CXX="$CXX" \
                      AR="$AR" \
                      RANLIB="$RANLIB" \
                      READELF="$READELF"

          echo "Configuration completed"
          make -j$(nproc)

      - name: Compile zlib
        run: |
          cd zlib-1.2.13
          CC="$CC" ./configure --prefix=$GITHUB_WORKSPACE/android-rootfs/data
          make -j$(nproc)

      - name: Install Python and zlib
        run: |
          mkdir -p $GITHUB_WORKSPACE/android-rootfs/data
          
          cd cpython
          make install prefix=$GITHUB_WORKSPACE/android-rootfs/data
          
          cd ../zlib-1.2.13
          make install

      - name: Package and Upload Artifacts
        run: |
          tar -czvf python-zlib-android-data.tar.gz -C android-rootfs/data .
          
      - uses: actions/upload-artifact@v4
        with:
          name: python-zlib-android-data
          path: python-zlib-android-data.tar.gz